version: '3.9'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - testing-network
    volumes:
      - ./app:/app
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: test_db

  db:
    image: 'postgres:14-alpine'
    restart: always
    ports:
      - "5432:5432"
    networks:
      - testing-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data