version: '3.9'
services:
  db:
    image: 'postgres:14-alpine'
    restart: always
    ports:
      - "5432:5432"
    networks:
      - testing-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - testing-network
    volumes:
      - ./app:/app
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: test_db

  tests:
    image: python:3.10
    depends_on:
      - db
    networks:
      - testing-network
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: test_db
      BACKEND_URL: http://app
      SMTP_SERVER: ${SMTP_SERVER}  # Pasa las variables desde el entorno
      SMTP_SERVER_PORT: ${SMTP_SERVER_PORT}
      SMTP_SERVER_USERNAME: ${SMTP_SERVER_USERNAME}
      SMTP_SERVER_PASSWORD: ${SMTP_SERVER_PASSWORD}
    command: bash -c "pip install behave==1.2.6 pydantic_settings==2.3.1 sqlalchemy==1.4.45 psycopg2==2.9.9 && behave"
    
networks:
  testing-network: