name: Build, Test and Publish Image To DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Step 1: Build Docker image
    - name: Build
      run: docker build . -t ramoro/convocarte-backend-docker-hub:latest

    # Step 2: Set up PostgreSQL container for tests
    # Necesario pasar las variables de entorno del SMTP_SERVER para que no falle
    - name: Start test services with Docker Compose
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_SERVER_PORT: ${{ secrets.SMTP_SERVER_PORT }}
        SMTP_SERVER_USERNAME: ${{ secrets.SMTP_SERVER_USERNAME }}
        SMTP_SERVER_PASSWORD: ${{ secrets.SMTP_SERVER_PASSWORD }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: docker compose -f docker-compose.test.yml up -d

    # Step 4: Wait for the app to be ready
    - name: Wait for the app to be ready
      run: |
        echo "Waiting for the app to be ready..."
        sleep 15  # Ajusta según sea necesario

    # Step 4: Run Behave tests inside Docker
    # Necesario pasar las variables de entorno del SMTP_SERVER para que no falle
    - name: Run Behave tests
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_SERVER_PORT: ${{ secrets.SMTP_SERVER_PORT }}
        SMTP_SERVER_USERNAME: ${{ secrets.SMTP_SERVER_USERNAME }}
        SMTP_SERVER_PASSWORD: ${{ secrets.SMTP_SERVER_PASSWORD }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: docker compose -f docker-compose.test.yml run tests

    # Step 5: Stop and remove Docker containers
    - name: Stop and remove Docker containers
      run: docker compose -f docker-compose.test.yml down

    # Step 7: Login to DockerHub and publish image
    - name: Publish
      run: |
       docker login -u ramoro -p ${{ secrets.DOCKERHUB_TOKEN }}
       docker push ramoro/convocarte-backend-docker-hub:latest

    # Step 8: Deploy (only on main branch)
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl "$deploy_url"