name: Build, Test and Publish Image To DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    # Step 1: Build Docker image
    - name: build
      run: docker build . -t ramoro/convocarte-backend-docker-hub:latest

    # Step 2: Set up PostgreSQL container for tests
    - name: Start test services with Docker Compose
      run: docker compose up -d

    # Step 4: Wait for the app to be ready
    - name: Wait for the app to be ready
      run: |
        echo "Waiting for the app to be ready..."
        sleep 15  # Ajusta según sea necesario

    # Step 5: Run Behave tests
    - name: Run Behave tests
      env:
        DATABASE_HOSTNAME: test_db
        DATABASE_PORT: 5432
        DATABASE_USERNAME: root
        DATABASE_NAME: test_db
        DATABASE_PASSWORD: root
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_SERVER_PORT: ${{ secrets.SMTP_SERVER_PORT }}
        SMTP_SERVER_USERNAME: ${{ secrets.SMTP_SERVER_USERNAME }}
        SMTP_SERVER_PASSWORD: ${{ secrets.SMTP_SERVER_PASSWORD }}
        BACKEND_URL: http://localhost:8000  # Usamos localhost ya que los tests corren en el host del runner
      run: |
        pip install behave==1.2.6 pydantic_settings==2.3.1 sqlalchemy==1.4.45 psycopg2==2.9.9
        cd app
        behave

    # Step 6: Stop and remove Docker containers
    - name: Stop and remove Docker containers
      run: |
        docker stop myapp test_db
        docker rm myapp test_db

    # Step 7: Login to DockerHub and publish image
    - name: publish
      run: |
       docker login -u ramoro -p ${{ secrets.DOCKERHUB_TOKEN }}
       docker push ramoro/convocarte-backend-docker-hub:latest

    # Step 8: Deploy (only on main branch)
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl "$deploy_url"